program:-
   write('==>  Hello Please Enter y if you have foloowing symptom \n  ==>Else press n'),nl,
   write('==>  Weakness  ==>  '),
   read(A),
   write('==>  Headach  ==>  '),
   read(B),
   write('==>  High Temprature  ==>  '),
   read(C),
   write('==>  Runny Nose  ==>  '),
   read(D),
   write('==>  Cough  ==>  '),
   read(E),
   write('==>  Sneezing  ==>  '),
   read(F),
   write('==>  fever  ==>  '),
   read(G),
   write('==>  Stomach Cramp  ==>  '),
   read(H),
   write('==>  Extreme Fatigue  ==>  '),
   read(I),
   write('==>  Body Ache  ==>  '),
   read(J),
   write('==>  Painfull Blisters on feet and Mouth  ==>  '),
   read(K),
   write('==>  Blisters On whole Body  ==>  '),
   read(L),
    write('==>  Red itchy and watery eyes  ==>  '),
   read(M),
    write('==>  Nausea ==>  '),
   read(N),
    write('==>  Pus ==>  '),
   read(O),
    write('==>  Tummy Aches  ==>  '),
   read(P),
    write('==>  Sore Throat  ==>  '),
   read(Q),
    write('==>  Dehaydration  ==>  '),
   read(R),
    write('==>  Diahhroea ==>  '),
   read(S).


